# Generated by Django 4.2.2 on 2023-06-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductDetails",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_image1", models.ImageField(upload_to="product_images/")),
                (
                    "product_image2",
                    models.ImageField(blank=True, upload_to="product_images/"),
                ),
                (
                    "product_image3",
                    models.ImageField(blank=True, upload_to="product_images/"),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("product_description", models.TextField()),
                ("product_price", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
