# Generated by Django 4.2.2 on 2023-06-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecomapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productdetails",
            name="product_description",
        ),
        migrations.AddField(
            model_name="productdetails",
            name="product_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="productdetails",
            name="product_quantity",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
