# Generated by Django 4.2.1 on 2023-06-20 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecomapp', '0002_remove_productdetails_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='product_image1',
            field=models.ImageField(blank=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='product_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='CartView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.productdetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
