# Generated by Django 4.2.1 on 2023-06-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_userdetails_alter_productdetails_product_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='password',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
